# variable "aws_region" {
#   description = "Target AWS region, where to provision resources"
#   type        = string
# }

# variable "desiredstate" {
#   description = "GitOps metadata for this Terraform root module"
# }

# variable "project_properties_global" {
#   description = "Project properties independent from the target environment and resources being provisioned"
#   type        = map(string)
# }

# variable "project_properties_env" {
#   description = "Project properties independent from the target environment and resources being provisioned"
#   type        = map(string)
# }

# variable "project_properties_proj" {
#   description = "Project properties specific to the target environment"
#   type        = map(string)
# }

# variable "resource" {
#   description = "Property for the resource being provisioned"
# }

# variable "custom_tags" {
#   description = "Custom tags, to be added together with the ones that will be autogenerated"
#   type        = map(string)
#   default     = {}
# }

# variable "custom_tags_verbatim" {
#   description = "Custom tags, to be added together vebatim with the ones that will be autogenerated"
#   type        = map(string)
#   default     = {}
# }
